openapi: 3.1.0
info:
  title: BBA Workout Validator
  version: 1.0.0
servers:
  - url: https://api.yourdomain.com

paths:
  /validate_workout:
    post:
      operationId: validateWorkout
      summary: Validate a generated workout against schema and rules
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Workout"
      responses:
        '200':
          description: Validation result
          content:
            application/json:
              schema:
                type: object
                required: [passed, violations]
                properties:
                  passed:
                    type: boolean
                  violations:
                    type: array
                    items:
                      type: object
                      properties:
                        code: { type: string }
                        message: { type: string }
                        path: { type: string }

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key

  schemas:
    Workout:
      $ref: "https://raw.githubusercontent.com/BenjaminBBA/bba-schemas/main/workout-v1.json"
